Update R-CMD-check-historic-R-versions.yaml

diff --git a/.github/workflows/R-CMD-check-historic-R-versions.yaml b/.github/workflows/R-CMD-check-historic-R-versions.yaml
--- a/.github/workflows/R-CMD-check-historic-R-versions.yaml
+++ b/.github/workflows/R-CMD-check-historic-R-versions.yaml
@@ -1,14 +1,18 @@
-# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
-# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
-#
-# NOTE: This workflow is overkill for most R packages and
-# check-standard.yaml is likely a better choice.
+# NOTE: This workflow is overkill for most R packages
+# check-standard.yaml is likely a better choice
 # usethis::use_github_action("check-standard") will install it.
+#
+# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
+# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
 on:
   push:
-    branches: [main, master]
+    branches:
+      - main
+      - master
   pull_request:
-    branches: [main, master]
+    branches:
+      - main
+      - master
 
 name: Historic-R-CMD-check
 
@@ -24,102 +28,73 @@ jobs:
         config:
           # - {os: macOS-latest,   r: 'release'}
           # - {os: windows-latest, r: 'release'}
-          # # Use older ubuntu to maximise backward compatibility
-          # - {os: ubuntu-18.04,   r: 'devel', http-user-agent: 'release'}
-          # - {os: ubuntu-18.04,   r: 'release'}
-          # - {os: ubuntu-18.04,   r: 'oldrel-1'}
+          # - {os: ubuntu-18.04,   r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest", http-user-agent: "R/4.1.0 (ubuntu-18.04) R (4.1.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions" }
+          # - {os: ubuntu-18.04,   r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
+          # - {os: ubuntu-18.04,   r: 'oldrel',  rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
+          # - {os: ubuntu-18.04,   r: '3.6',     rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
+          # - {os: ubuntu-18.04,   r: '3.5',     rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
+          # - {os: ubuntu-18.04,   r: '3.4',     rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
           - {os: ubuntu-18.04,   r: 'oldrel-2'}
           - {os: ubuntu-18.04,   r: 'oldrel-3'}
           - {os: ubuntu-18.04,   r: 'oldrel-4'}
-
     env:
+      RSPM: ${{ matrix.config.rspm }}
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
-      R_KEEP_PKG_SOURCE: yes
-      _R_CHECK_FORCE_SUGGESTS_: false
-      R_CHECK_FORCE_SUGGESTS_: false
 
     steps:
       - uses: actions/checkout@v2
 
-      - uses: r-lib/actions/setup-pandoc@v1
-
       - uses: r-lib/actions/setup-r@v1
+        id: install-r
         with:
           r-version: ${{ matrix.config.r }}
           http-user-agent: ${{ matrix.config.http-user-agent }}
-          use-public-rspm: true
 
-      # ------------------------------------------------------------------------
-      # copied from https://github.com/r-lib/actions/blob/master/setup-r-dependencies/action.yaml
-      # and modified not error when Suggested pkgs cannot be installed
-      # - uses: r-lib/actions/setup-r-dependencies@v1
-      #   with:
-      #     extra-packages: rcmdcheck
+      - uses: r-lib/actions/setup-pandoc@v1
+
       - name: Install pak and query dependencies
         run: |
-          cat("::group::Install pak\n")
-          options(pak.no_extra_messages = TRUE)
           install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
-          tryCatch(saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), ".github/r-depends.rds"), error = function(e) invisible())
+          saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), ".github/r-depends.rds")
         shell: Rscript {0}
 
-      - name: Get R and OS version
-        id: get-version
+      - name: Restore R package cache
+        uses: actions/cache@v2
+        with:
+          path: |
+            ${{ env.R_LIBS_USER }}/*
+            !${{ env.R_LIBS_USER }}/pak
+          key: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-${{ hashFiles('.github/r-depends.rds') }}
+          restore-keys: ${{ matrix.config.os }}-${{ steps.install-r.outputs.installed-r-version }}-1-
+
+      - name: Install system dependencies
+        if: runner.os == 'Linux'
         run: |
-          cat("::set-output name=os-version::", sessionInfo()$running, "\n", sep = "")
-          cat("::set-output name=r-version::", R.Version()$version.string, "\n", sep = "")
-          cat("::endgroup::\n")
+          pak::local_system_requirements(execute = TRUE)
+          pak::pkg_system_requirements("rcmdcheck", execute = TRUE)
         shell: Rscript {0}
-
-      # - name: Restore R package cache
-      #   uses: actions/cache@v2
-      #   with:
-      #     path: |
-      #       ${{ env.R_LIBS_USER }}/*
-      #       !${{ env.R_LIBS_USER }}/pak
-      #     key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-${{ hashFiles('.github/r-depends.rds') }}
-      #     restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-
 
       - name: Install dependencies
         run: |
-          cat("::group::Install dependencies\n")
-          tryCatch({
-            options(pak.no_extra_messages = TRUE)
-            local_deps <- pak::local_dev_deps(dependencies = "all")[["ref"]]
-            needs <- sprintf("Config/Needs/%s", strsplit("${{ inputs.needs }}", "[[:space:],]+")[[1]])
-            needs_deps <- pak::local_dev_deps(dependencies = needs)[["ref"]]
-            needs_only_deps <- setdiff(needs_deps, local_deps)
-            extra_deps <- strsplit("${{ inputs.extra-packages }}", "[[:space:],]+")[[1]]
-            if (Sys.info()[["sysname"]] == "Linux") {
-              pak::local_system_requirements(execute = TRUE)
-              for (dep in c(needs_only_deps, extra_deps)) {
-                pak::pkg_system_requirements(dep, execute = TRUE)
-              }
-            }
-            pak::pkg_install(c(local_deps, needs_only_deps, extra_deps, "sessioninfo", "rcmdcheck"))
-          },
-          error = function(e) NULL)
-          cat("::endgroup::\n")
+          pak::local_install_dev_deps(upgrade = TRUE)
+          pak::pkg_install("rcmdcheck")
         shell: Rscript {0}
 
       - name: Session info
         run: |
-          cat("::group::Session info\n")
           options(width = 100)
           pkgs <- installed.packages()[, "Package"]
           sessioninfo::session_info(pkgs, include_base = TRUE)
-          cat("::endgroup::\n")
         shell: Rscript {0}
 
-      - name: Don't use tar 1.30 from Rtools35 to store the cache
-        shell: bash
+      - name: Check
+        env:
+          _R_CHECK_FORCE_SUGGESTS_: false
+          _R_CHECK_CRAN_INCOMING_: false
         run: |
-          if command -v /c/Rtools/bin/tar && /c/Rtools/bin/tar --version | grep -q 'tar (GNU tar) 1.30'
-            then echo 'C:/Program Files/Git/usr/bin' >> $GITHUB_PATH
-          fi
-      # ------------------------------------------------------------------------
-
-      - uses: r-lib/actions/check-r-package@v1
+          options(crayon.enabled = TRUE)
+          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
+        shell: Rscript {0}
 
       - name: Show testthat output
         if: always()
@@ -130,5 +105,163 @@ jobs:
         if: failure()
         uses: actions/upload-artifact@main
         with:
-          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+          name: ${{ matrix.config.os }}-r${{ matrix.config.r }}-results
           path: check
+
+      - name: Don't use tar from old Rtools to store the cache
+        if: ${{ runner.os == 'Windows' && startsWith(steps.install-r.outputs.installed-r-version, '3.6' ) }}
+        shell: bash
+        run: echo "C:/Program Files/Git/usr/bin" >> $GITHUB_PATH
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+# # Workflow derived from https://github.com/r-lib/actions/tree/master/examples
+# # Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
+# #
+# # NOTE: This workflow is overkill for most R packages and
+# # check-standard.yaml is likely a better choice.
+# # usethis::use_github_action("check-standard") will install it.
+# on:
+#   push:
+#     branches: [main, master]
+#   pull_request:
+#     branches: [main, master]
+#
+# name: Historic-R-CMD-check
+#
+# jobs:
+#   R-CMD-check:
+#     runs-on: ${{ matrix.config.os }}
+#
+#     name: ${{ matrix.config.os }} (${{ matrix.config.r }})
+#
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         config:
+#           # - {os: macOS-latest,   r: 'release'}
+#           # - {os: windows-latest, r: 'release'}
+#           # # Use older ubuntu to maximise backward compatibility
+#           # - {os: ubuntu-18.04,   r: 'devel', http-user-agent: 'release'}
+#           # - {os: ubuntu-18.04,   r: 'release'}
+#           # - {os: ubuntu-18.04,   r: 'oldrel-1'}
+#           - {os: ubuntu-18.04,   r: 'oldrel-2'}
+#           - {os: ubuntu-18.04,   r: 'oldrel-3'}
+#           - {os: ubuntu-18.04,   r: 'oldrel-4'}
+#
+#     env:
+#       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+#       R_KEEP_PKG_SOURCE: yes
+#       _R_CHECK_FORCE_SUGGESTS_: false
+#       R_CHECK_FORCE_SUGGESTS_: false
+#
+#     steps:
+#       - uses: actions/checkout@v2
+#
+#       - uses: r-lib/actions/setup-pandoc@v1
+#
+#       - uses: r-lib/actions/setup-r@v1
+#         with:
+#           r-version: ${{ matrix.config.r }}
+#           http-user-agent: ${{ matrix.config.http-user-agent }}
+#           use-public-rspm: true
+#
+#       # ------------------------------------------------------------------------
+#       # copied from https://github.com/r-lib/actions/blob/master/setup-r-dependencies/action.yaml
+#       # and modified not error when Suggested pkgs cannot be installed
+#       # - uses: r-lib/actions/setup-r-dependencies@v1
+#       #   with:
+#       #     extra-packages: rcmdcheck
+#       - name: Install pak and query dependencies
+#         run: |
+#           cat("::group::Install pak\n")
+#           options(pak.no_extra_messages = TRUE)
+#           install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")
+#           tryCatch(saveRDS(pak::pkg_deps("local::.", dependencies = TRUE), ".github/r-depends.rds"), error = function(e) invisible())
+#         shell: Rscript {0}
+#
+#       - name: Get R and OS version
+#         id: get-version
+#         run: |
+#           cat("::set-output name=os-version::", sessionInfo()$running, "\n", sep = "")
+#           cat("::set-output name=r-version::", R.Version()$version.string, "\n", sep = "")
+#           cat("::endgroup::\n")
+#         shell: Rscript {0}
+#
+#       # - name: Restore R package cache
+#       #   uses: actions/cache@v2
+#       #   with:
+#       #     path: |
+#       #       ${{ env.R_LIBS_USER }}/*
+#       #       !${{ env.R_LIBS_USER }}/pak
+#       #     key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-${{ hashFiles('.github/r-depends.rds') }}
+#       #     restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-
+#
+#       - name: Install dependencies
+#         run: |
+#           cat("::group::Install dependencies\n")
+#           tryCatch({
+#             options(pak.no_extra_messages = TRUE)
+#             local_deps <- pak::local_dev_deps(dependencies = "all")[["ref"]]
+#             needs <- sprintf("Config/Needs/%s", strsplit("${{ inputs.needs }}", "[[:space:],]+")[[1]])
+#             needs_deps <- pak::local_dev_deps(dependencies = needs)[["ref"]]
+#             needs_only_deps <- setdiff(needs_deps, local_deps)
+#             extra_deps <- strsplit("${{ inputs.extra-packages }}", "[[:space:],]+")[[1]]
+#             if (Sys.info()[["sysname"]] == "Linux") {
+#               pak::local_system_requirements(execute = TRUE)
+#               for (dep in c(needs_only_deps, extra_deps)) {
+#                 pak::pkg_system_requirements(dep, execute = TRUE)
+#               }
+#             }
+#             pak::pkg_install(c(local_deps, needs_only_deps, extra_deps, "sessioninfo", "rcmdcheck"))
+#           },
+#           error = function(e) NULL)
+#           cat("::endgroup::\n")
+#         shell: Rscript {0}
+#
+#       - name: Session info
+#         run: |
+#           cat("::group::Session info\n")
+#           options(width = 100)
+#           pkgs <- installed.packages()[, "Package"]
+#           sessioninfo::session_info(pkgs, include_base = TRUE)
+#           cat("::endgroup::\n")
+#         shell: Rscript {0}
+#
+#       - name: Don't use tar 1.30 from Rtools35 to store the cache
+#         shell: bash
+#         run: |
+#           if command -v /c/Rtools/bin/tar && /c/Rtools/bin/tar --version | grep -q 'tar (GNU tar) 1.30'
+#             then echo 'C:/Program Files/Git/usr/bin' >> $GITHUB_PATH
+#           fi
+#       # ------------------------------------------------------------------------
+#
+#       - uses: r-lib/actions/check-r-package@v1
+#
+#       - name: Show testthat output
+#         if: always()
+#         run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+#         shell: bash
+#
+#       - name: Upload check results
+#         if: failure()
+#         uses: actions/upload-artifact@main
+#         with:
+#           name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+#           path: check
